/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_yintaibing_avstudy_test_JniTest */

#ifndef _Included_me_yintaibing_avstudy_test_JniTest
#define _Included_me_yintaibing_avstudy_test_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_yintaibing_avstudy_test_JniTest
 * Method:    stringFromJNI
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_yintaibing_avstudy_test_JniTest_nativeStringFromJNI
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
