/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_yintaibing_avstudy_test_JniTest */

#ifndef _Included_me_yintaibing_avstudy_video_Mp4Decoder
#define _Included_me_yintaibing_avstudy_video_Mp4Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_yintaibing_avstudy_video_Mp4Decoder
 */
JNIEXPORT void JNICALL Java_me_yintaibing_avstudy_video_Mp4FFmpegPlayer_decodeMp4
        (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
